# Generated by Django 3.1.7 on 2021-03-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_ogranisation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='previous_organisation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
